---
title: "Lesson 5: Multivariate Analysis"
author: "Josh Goldberg"
date: "October 29, 2017"
output: github_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      warning=FALSE, message=FALSE)
```

```{r Load Libraries}
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
library(data.table)

```


```{r Price Histograms with Facet and Color}
# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')

# load dataset
data(diamonds)

# name variables
names(diamonds)

# structure of dataset
glimpse(diamonds)
levels(diamonds$clarity)

# reorganize levels of ordered factors in ascending order
levels(diamonds$color) = c('J', 'I', 'H', 'G', 'F', 'E', 'D')
levels(diamonds$clarity) = c('I1', 'SI1', 'SI2', 'VS1', 'VS2', 'VVS1', 'VVS2', 'IF')

# plot
ggplot(aes(x = log10(price), fill = cut), data = diamonds) +
  labs(x = 'Price', y = 'Frequency',
       title = 'Price of Diamonds by Color and Cut') +
  geom_histogram(bidwith = .01) +
  facet_wrap( ~ color)

  

```

